"""Add PriceHistory table and fix constraints

Revision ID: 9055102c507c
Revises: e1d1a8f6c039
Create Date: 2026-02-20 19:57:07.347586

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9055102c507c"
down_revision: Union[str, Sequence[str], None] = "e1d1a8f6c039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history", sa.Column("discount_percent", sa.Integer(), nullable=False)
    )
    op.add_column(
        "price_history",
        sa.Column(
            "scraped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "price_history",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_price_history_timestamp"), table_name="price_history")
    op.create_index(
        op.f("ix_price_history_scraped_at"),
        "price_history",
        ["scraped_at"],
        unique=False,
    )
    op.drop_constraint(
        op.f("price_history_listing_id_fkey"), "price_history", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "price_history",
        "game_listings",
        ["listing_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("price_history", "timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history",
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "price_history", type_="foreignkey")
    op.create_foreign_key(
        op.f("price_history_listing_id_fkey"),
        "price_history",
        "game_listings",
        ["listing_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_price_history_scraped_at"), table_name="price_history")
    op.create_index(
        op.f("ix_price_history_timestamp"), "price_history", ["timestamp"], unique=False
    )
    op.alter_column(
        "price_history",
        "price",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("price_history", "scraped_at")
    op.drop_column("price_history", "discount_percent")
    # ### end Alembic commands ###
